import "./globals.css";
import Navbar from "./components/Navbar";
import { Poppins } from 'next/font/google'
import { ToastContainer } from "react-toastify";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({ 
  weight: ['400','500','700'], 
  subsets: ['latin'] 
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <ToastContainer />

      </body>
    </html>
  );
}
